"""Builds the SLA outage report .docx files with python-docx, reproducing
the layout of the real Week 3 example reports (data/samples/sla_week3/):
title/subtitle/generated-by line, an intro paragraph, numbered sections
with "Light Grid Accent 1" tables (same style utils/report_generator.py's
add_table_to_word() already uses elsewhere in this app), 1x4 key-figure
boxes, a "DRAFT FOR REVIEW" header, and the approval block (line of
underscores, then the typed name/title/organisation).

build_docx(kind, facts, tables, text, signatory) -> bytes is the only
entry point the page needs; kind is "regional" or "management".
"""
from __future__ import annotations

import io

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor

HEADER_FILL = "4472C4"


def _num(v, decimals=2) -> str:
    if v is None:
        return ""
    try:
        return f"{float(v):,.{decimals}f}"
    except (TypeError, ValueError):
        return str(v)


def _naira(v) -> str:
    return f"₦{_num(v)}" if v is not None else ""


def _set_draft_header(doc: Document):
    section = doc.sections[0]
    header = section.header
    p = header.paragraphs[0] if header.paragraphs else header.add_paragraph()
    p.text = "DRAFT FOR REVIEW"
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in p.runs:
        run.font.bold = True
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0xB3, 0x26, 0x1E)


def _title_block(doc: Document, title: str, subtitle: str):
    t = doc.add_paragraph()
    run = t.add_run(title)
    run.font.size = Pt(20)
    run.font.bold = True
    doc.add_paragraph(subtitle)
    doc.add_paragraph("This report was generated by the TCN Operations Department Outage Report & Analytics Software.")


def _para(doc: Document, text: str):
    if text and text.strip():
        doc.add_paragraph(text.strip())


def _bulleted(doc: Document, text: str):
    """Each blank-line-separated chunk becomes its own "List Paragraph",
    matching the real reports' Root Cause Notes / Key Observations /
    Recommendations style."""
    if not text or not text.strip():
        return
    for chunk in text.split("\n\n"):
        chunk = chunk.strip()
        if chunk:
            doc.add_paragraph(chunk, style="List Paragraph")


def _key_figure_boxes(doc: Document, pairs: list[tuple[str, str]]):
    """A single 1-row table with one (label, value) pair per cell,
    matching the real reports' 1x4 key-figure boxes."""
    table = doc.add_table(rows=1, cols=len(pairs))
    table.style = "Table Grid"
    for cell, (label, value) in zip(table.rows[0].cells, pairs):
        p1 = cell.paragraphs[0]
        r1 = p1.add_run(label)
        r1.font.bold = True
        r1.font.size = Pt(8)
        p2 = cell.add_paragraph()
        r2 = p2.add_run(value)
        r2.font.size = Pt(14)
        r2.font.bold = True
    doc.add_paragraph()


def _table(doc: Document, headers: list[str], rows: list[list[str]], title: str | None = None):
    if title:
        doc.add_paragraph(title, style="Heading 2")
    if not rows:
        doc.add_paragraph("None this period.")
        return
    table = doc.add_table(rows=len(rows) + 1, cols=len(headers))
    table.style = "Light Grid Accent 1"
    hdr = table.rows[0].cells
    for i, h in enumerate(headers):
        hdr[i].text = h
        for para in hdr[i].paragraphs:
            for run in para.runs:
                run.font.bold = True
                run.font.color.rgb = RGBColor(255, 255, 255)
            shd = OxmlElement("w:shd")
            shd.set(qn("w:fill"), HEADER_FILL)
            hdr[i]._element.get_or_add_tcPr().append(shd)
    for ridx, row in enumerate(rows, start=1):
        cells = table.rows[ridx].cells
        for cidx, val in enumerate(row):
            cells[cidx].text = str(val)
    doc.add_paragraph()


def _heading(doc: Document, text: str, level: int = 1):
    doc.add_heading(text, level=level)


def _approval(doc: Document, signatory: dict, heading: str = "Approval"):
    _heading(doc, heading)
    doc.add_paragraph("This report was reviewed and is hereby submitted for Management's consideration.")
    doc.add_paragraph("_" * 33)
    doc.add_paragraph(signatory.get("name", ""))
    doc.add_paragraph(signatory.get("title", ""))
    doc.add_paragraph(signatory.get("organisation", "Transmission Company of Nigeria"))


def _assumptions_appendix(doc: Document, facts: dict):
    doc.add_page_break()
    _heading(doc, "Appendix: Assumptions and Overrides")
    assumed = facts.get("assumed_band_feeders") or []
    _table(doc, ["Station", "Feeder"], [[r["station"], r["feeder"]] for r in assumed],
           title=f"Feeders priced as Band A (assumed) -- {len(assumed)}")
    unknown = facts.get("disco_unknown_feeders") or []
    _table(doc, ["Station", "Feeder"], [[r["station"], r["feeder"]] for r in unknown],
           title=f"Feeders with DisCo unknown, excluded from cost -- {len(unknown)}")
    overrides = facts.get("overrides_used") or []
    _table(doc, ["Station", "Feeder", "From", "To", "Reason"],
           [[o["station"], o["feeder"], o["date_from"], o["date_to"], o["reason"]] for o in overrides],
           title=f"Allowance overrides applied -- {len(overrides)}")


def build_regional_docx(facts: dict, tables: dict, text: dict, signatory: dict) -> bytes:
    doc = Document()
    _set_draft_header(doc)
    region = facts["region"]
    _title_block(doc, f"33kV Feeder Outage Report — {region} Region",
                 f"{facts['period_label']}  |  Reporting Period: {facts['period_start']} to {facts['period_end']}  |  "
                 f"Scope: TCN-attributed 33kV feeder interruptions")
    _para(doc, text.get("intro"))

    _heading(doc, "1. Executive Summary")
    _key_figure_boxes(doc, [
        ("NUMBER OF OUTAGES", str(facts["outages"])),
        ("TOTAL OUTAGE HOURS", _num(facts["hours"])),
        ("TOTAL LOAD LOSS", f"{_num(facts['load_loss_mwh'])} MWh"),
    ])
    _heading(doc, "1.1 Outage Cause Distribution", level=2)
    _table(doc, ["Cause", "Share of Outages (%)"],
           [[c["cause"], f"{c['share_pct']}%"] for c in facts["cause_share"]])
    _para(doc, text.get("cause_note"))

    _heading(doc, "2. Top Stations by Outage Minutes")
    _table(doc, ["Station", "Outages", "Total Min", "Avg Min", "Total Load Loss (MWh)", "Avg Load Loss (MWh)"],
           [[r["station"], r["outages"], _num(r["total_min"]), _num(r["avg_min"]),
             _num(r["load_loss_mwh"]), _num(r["avg_load_loss_mwh"])] for r in tables["top_stations"]])

    _heading(doc, "3. Top Feeders by Outage Hours")
    _table(doc, ["Feeder (Station)", "Outages", "Total Hrs", "Avg Hrs", "Total Load Loss (MWh)"],
           [[f"{r['feeder']} ({r['station']})", r["outages"], _num(r["total_hrs"]), _num(r["avg_hrs"]),
             _num(r["load_loss_mwh"])] for r in tables["top_feeders"]])

    _heading(doc, "4. SLA Compliance — Allowable Outage Hours by Band")
    _para(doc, text.get("sla_note"))
    _table(doc, ["Station", "Feeder", "Band", "TCN Hrs", "Allocation (Hrs)", "Available (Hrs)"],
           [[r["station"], r["feeder"], r["band"] + (" (assumed)" if r["band_assumed"] else ""),
             _num(r["tcn_hrs"]), _num(r["allocation_hrs"]), _num(r["available_hrs"])] for r in tables["compliance"]])

    _heading(doc, "5. TCN Outage-Hour Allocation Exceedance & Estimated Cost")
    _para(doc, text.get("exceedance_note"))
    over = tables["exceedance"]
    _key_figure_boxes(doc, [
        ("FEEDERS OVER ALLOCATION", str(facts["feeders_over_allocation"])),
        ("TOTAL EXCESS HOURS", f"{_num(facts['excess_hrs'])} hrs"),
        ("TOTAL EXCESS LOAD LOSS", f"{_num(facts['excess_load_loss_mwh'])} MWh"),
        ("ESTIMATED COST", _naira(facts["estimated_cost_ngn"])),
    ])
    _table(doc, ["Station", "Feeder", "Band", "TCN Hrs", "Allocation (Hrs)", "Excess Hrs", "Excess Loss (MWh)", "Est. Cost (₦)"],
           [[r["station"], r["feeder"], r["band"] + (" (assumed)" if r["band_assumed"] else ""), _num(r["tcn_hrs"]),
             _num(r["allocation_hrs"]), _num(r["excess_hrs"]), _num(r["excess_load_loss_mwh"]),
             _naira(r["estimated_cost_ngn"])] for r in over])

    n = 6
    if text.get("root_cause_notes", "").strip():
        _heading(doc, f"{n}. Root Cause Notes")
        doc.add_paragraph("These notes come from a feeder-by-feeder review of the underlying interruption log "
                          f"for {facts['period_start']} to {facts['period_end']}, so the actual cause behind each "
                          "outage can be addressed directly.")
        _bulleted(doc, text["root_cause_notes"])
        n += 1

    if facts.get("at_risk_feeders"):
        _heading(doc, f"{n}. Feeders at Risk This Month")
        _table(doc, ["Station", "Feeder", "Band", "Month-to-Date TCN Hrs", "Allocation (Hrs)", "% Used"],
               [[r["station"], r["feeder"], r["band"] + (" (assumed)" if r["band_assumed"] else ""),
                 _num(r["tcn_hrs"]), _num(r["allocation_hrs"]), f"{r['used_pct']*100:.0f}%"]
                for r in facts["at_risk_feeders"]])
        _para(doc, text.get("at_risk_note"))
        n += 1

    if text.get("intervention_note", "").strip():
        _heading(doc, f"{n}. Key Intervention / Loss Prevention Actions by Operations Department")
        doc.add_paragraph("This section documents corrective action the Operations Department has already taken "
                          "in response to a finding from this analysis.")
        _bulleted(doc, text["intervention_note"])
        n += 1

    _assumptions_appendix(doc, facts)
    _approval(doc, signatory, heading=f"{n}. Approval")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_management_docx(facts: dict, tables: dict, text: dict, signatory: dict) -> bytes:
    doc = Document()
    _set_draft_header(doc)
    _title_block(doc, "TCN Network Outage & SLA Exceedance Report",
                 f"Management Summary — {facts['period_label']}  |  Reporting Period: {facts['period_start']} "
                 f"to {facts['period_end']}  |  All Regions")
    _para(doc, text.get("intro"))
    _para(doc, text.get("important_note"))

    _heading(doc, "Network-Wide Outage Cause Distribution", level=2)
    _table(doc, ["Cause", "Share of Outages (%)"],
           [[c["cause"], f"{c['share_pct']}%"] for c in facts["cause_share"]])
    _para(doc, text.get("cause_note"))

    _heading(doc, f"1. Network-Wide Key Performance Indicators ({facts['period_label']})")
    _key_figure_boxes(doc, [
        ("TOTAL OUTAGES", str(facts["outages"])),
        ("TOTAL OUTAGE HOURS", _num(facts["hours"])),
        ("TOTAL LOAD LOSS", f"{_num(facts['load_loss_mwh'])} MWh"),
        ("REGIONS REPORTING", str(facts["regions"])),
    ])
    _heading(doc, "1.1 TCN Outage-Hour Allocation Exceedance (30% Fault Attribution Ratio)", level=2)
    _para(doc, text.get("kpi_note"))
    _key_figure_boxes(doc, [
        ("FEEDERS OVER ALLOCATION", str(facts["feeders_over_allocation"])),
        ("TOTAL EXCESS HOURS", f"{_num(facts['excess_hrs'])} hrs"),
        ("TOTAL EXCESS LOAD LOSS", f"{_num(facts['excess_load_loss_mwh'])} MWh"),
        ("ESTIMATED TOTAL COST EXPOSURE", _naira(facts["estimated_cost_ngn"])),
    ])

    _heading(doc, f"2. Region-by-Region Outage Summary ({facts['period_label']})")
    _table(doc, ["Region", "Outages", "Total Hrs", "Avg Duration (min)", "Load Loss (MWh)"],
           [[r["region"], r["outages"], _num(r["total_hrs"]), _num(r["avg_duration_min"]),
             _num(r["load_loss_mwh"])] for r in facts["region_summary"]])

    _heading(doc, f"3. TCN Allowable Outage Duration Exceedance by Region ({facts['period_label']})")
    _para(doc, text.get("region_exceedance_note"))
    _table(doc, ["Region", "Feeders Over Allocation", "Excess Hours", "Excess Load Loss (MWh)", "Estimated Cost (₦)"],
           [[r["region"], r["feeders_over"], _num(r["excess_hrs"]), _num(r["excess_load_loss_mwh"]),
             _naira(r["estimated_cost_ngn"])] for r in facts["exceedance_by_region"]])

    _heading(doc, f"4. Top 10 Highest-Cost Feeder Exceedances — {facts['period_label']} (All Regions)")
    _para(doc, text.get("top_cost_note"))
    _table(doc, ["Station", "Region", "Feeder", "TCN Hrs", "Excess Hrs", "Excess Loss (MWh)", "Est. Cost (₦)"],
           [[r["station"], r.get("region", ""), r["feeder"], _num(r["tcn_hrs"]), _num(r["excess_hrs"]),
             _num(r["excess_load_loss_mwh"]), _naira(r["estimated_cost_ngn"])] for r in facts["top_cost_feeders"]])

    _heading(doc, "5. Comparative Performance (Issued Periods)")
    _para(doc, text.get("comparative_note"))
    _table(doc, ["Metric"] + [p["period_label"] for p in tables.get("issued_periods", [])],
           tables.get("comparative_rows", []))
    _heading(doc, "5.1 Exceedance Cost by Region (Issued Periods)", level=2)
    _table(doc, ["Region"] + [p["period_label"] for p in tables.get("issued_periods", [])],
           tables.get("comparative_region_rows", []))

    _heading(doc, "6. Aggregate Performance — Month to Date")
    _para(doc, text.get("aggregate_note"))
    _key_figure_boxes(doc, [
        ("FEEDERS OVER ALLOCATION (MTD)", str(len(tables.get("mtd_exceedance", [])))),
        ("ESTIMATED TOTAL COST", _naira(facts.get("mtd_estimated_cost_ngn"))),
    ])
    _heading(doc, "6.3 Top 10 Highest-Cost Feeders — Month-to-Date Cumulative", level=2)
    _table(doc, ["Station", "Feeder", "MTD TCN Hrs", "Excess Hrs", "Excess Loss (MWh)", "Est. Cost (₦)"],
           tables.get("mtd_top_cost_rows", []))

    n = 7
    if text.get("key_observations", "").strip():
        _heading(doc, f"{n}. Key Observations")
        _bulleted(doc, text["key_observations"])
        n += 1

    if text.get("intervention_note", "").strip():
        _heading(doc, f"{n}. Key Intervention / Loss Prevention Actions by Operations Department")
        _bulleted(doc, text["intervention_note"])
        n += 1

    if text.get("recommendations", "").strip():
        _heading(doc, f"{n}. Recommendations")
        _bulleted(doc, text["recommendations"])
        n += 1
    _para(doc, text.get("closing_note"))

    _assumptions_appendix(doc, facts)
    _approval(doc, signatory, heading=f"{n}. Approval")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_docx(kind: str, facts: dict, tables: dict, text: dict, signatory: dict) -> bytes:
    if kind == "regional":
        return build_regional_docx(facts, tables, text, signatory)
    if kind == "management":
        return build_management_docx(facts, tables, text, signatory)
    raise ValueError(f"unknown kind: {kind}")
